secret:
    rustfs:
        access_key: ENC[AES256_GCM,data:6vyDm0uWscO5JXky7Qb1SA==,iv:217JZk4YXDHSWeyP4M44UXzJBkFdaRUsUVrp7DYVdEE=,tag:He4IPA8kUEbrOWB+j6pZDQ==,type:str]
        secret_key: ENC[AES256_GCM,data:sKwW5jyug2dADt/dmHQm,iv:hU5YWluETWhqxzhihEV6JaAlLISofIqOEfNmX1w8vPo=,tag:VeLbrkKUCRrcKX89xFO0fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150ragpc4lx6lnerxmk8azclsc5jwwz984ewfgdlxtm9k6z0a7smqgwx66l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAramFoazNuaWFldXRMZ3Y4
            aE1UbDErWGFPSTVzcUdaQllZK05qZisveWdzCkVNekVNT1dQekVrcU8zdzFESUJz
            OVBEalg1bEFReUgxaXdWUzNwU282UVUKLS0tIDdZL1FvckFuaU5zQTI0Y0RuVXJz
            SjZNSURZYktjSnA0UldoRXJDekpMbDAKxFMbf2B3vRh+W3y0B4q6ioFt8aPbhFdK
            gqXeAus+QeDB5M3tw4PLkzLcFa/Is+/bKAZEAufs+t4Ol7LeCoF4tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T04:41:38Z"
    mac: ENC[AES256_GCM,data:IDm4e8oUrBC1MxP/k5zG80vOGQffi0bNHg1UwtLMW8OeKe5e0KVNyhAyLqXQSNCqC7ze8TUhIy8If1IQguK3qxd/xy4rbGeqTZkR80747Sf9pA/Ar1lIYTGiya4gId4VWzlacc97W8c/GxhY9MeUf0MpsL2XaRnV9T9cEZNDNmc=,iv:LjOU8F1TWhhdCaeaokkis7KM8Xuq2H0hcXHZ53R6Mw0=,tag:tzJQ6OK6yUSKP4UnOQk3cQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
