apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.grafana.instanceSelector.matchLabels | indent 4 }}
spec:
{{ toYaml .Values.grafana.spec | indent 2 }}
