grafana:
  instanceSelector:
    matchLabels:
      datasource: "grafana"
  spec:
    version: "12.2"
    config:
      log:
        mode: "console"
        level: "info"
      log.console:
        format: "json"
      server:
        root_url: http://grafana.homelab.local
        enable_gzip: "true"
      # https://forums.percona.com/t/pmm-and-grafana-not-loading-same-in-browser-tab/11996
      auth:
        login_cookie_name: grafana_homelab_session
      security:
        admin_user: admin
        admin_password: admin
    persistentVolumeClaim:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    ingress:
      spec:
        ingressClassName: nginx
        rules:
          - host: grafana.homelab.local
            http:
              paths:
                - backend:
                    service:
                      name: grafana-service
                      port:
                        number: 3000
                  path: /
                  pathType: Prefix        