{
 "title": "[Screen 3] - OpenVPN Dashboard",
 "description": "OpenVPN Server status using Prometheus and OpenVPN exporter ",
 "tags": [
  "openvpn",
  "dummy"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "STATUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openvpn_server_connected_clients",
     "legendFormat": "Connected OpenVPN Clients"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-openvpn_status_update_time_seconds"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "table",
   "gridPos": { "h": 21, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "openvpn_server_client_received_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Traffic",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(6, sum(increase(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d])+increase(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))"
    }
   ]
  }
 ]
}