pilot:
  autoscaleEnabled: false
  replicaCount: 2
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
global:
  proxy:
    resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi