loki:
    structuredConfig:
        storage_config:
            named_stores:
                aws:
                    s3-loki-chunks:
                        access_key_id: ENC[AES256_GCM,data:dxnJuHtPPK0so/dootKyLg==,iv:LGFu7PQ/lc2eFKW/QUvCNSWz1IsQxTHV/5VyEO7IRGk=,tag:7rX5rJZYCaqQcIAY8C6TUg==,type:str]
                        secret_access_key: ENC[AES256_GCM,data:5hdqhqr5d5zyD70vqVa2,iv:Ckz6UI1iUlhRAwlejKR2hgJlp2l/tVD3RX6wq2uP6bc=,tag:KTS6ymdOuTjB9vXMm/jW3w==,type:str]
                    s3-loki-ruler:
                        access_key_id: ENC[AES256_GCM,data:W04R8kdPEruIyNIZpqRJPQ==,iv:MQyCLL0iHVPDS/M8Dz0ZYreOASCKLUsNbLG43YMFqvg=,tag:8WKl6jlLuwrdRKYvxoWP4w==,type:str]
                        secret_access_key: ENC[AES256_GCM,data:VbeiV6r1U9NCmaa33Ki2,iv:giswIy6v9ekCtCumivpXaNs5ODP4JN3xS2i6dFZ/B3E=,tag:1pXE8yUoH+dAaVVNrXsGTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150ragpc4lx6lnerxmk8azclsc5jwwz984ewfgdlxtm9k6z0a7smqgwx66l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MWVKTDJjZEJ5dHIzTm5u
            RVBZb3d1SGh2ZDZYZjRHcENZSUtYV08wSEI0CkgvQkVrTDREK1Rod0VEMkQranNu
            THQzbzVFUGJTZ1dnUjg5MW9nR21TS00KLS0tIHNpN0FMcHA0US9jb1IrYmR0WGJ5
            akxWZnNJakxpOEMwZC9OUDM2TGpJMk0K3CoP1myNsMUszxZhuFQ0tFC1bLrM1hGy
            YjR0+yDbQX4QmoaKdXEskhZyHzY2JbfPe7vsOKLm5uL6NsDSIRXrcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T05:30:40Z"
    mac: ENC[AES256_GCM,data:fOT4EKOJ5iCDbA2GCcgDCiA5hpx95SxNkSv6XnA1EmhTkq1JSZJccnzEFiyuqhHY75aSybvrvoE/92tL+qJ3mvRmIsUxUFIdenPr8SlLGd2LtJTGKPrUSsY50qmI5KCenfXdGD/SSiRO0OOluctE0twr0U+TomttsjMCSKOFvNQ=,iv:KO/utENWBYELhHdxf7BpwrUrAQYrbj6gnwnrFr+Rnm4=,tag:uniZxAkdfmnbCMEVSKQMAQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
