{
 "title": "[Screen 2] - dummy Service API Overview",
 "description": "Parsing Envoy access logs with Grafana Loki",
 "tags": [ "dummy" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "KPI's for domain *.dummy.io", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful Login",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"istio-proxy\"} \n| json \n| path = `/auth/login` \n| requested_server_name =~ `api-gateway.*.dummy.io` \n| response_code =~ `20[01]` \n| request_id != `` \n| __error__=`` \n[24h]))"
    }
   ]
  },
  {
   "title": "2xx requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"istio-proxy\"}\n| json\n| __error__=\"\"\n| authority =~ \".*dummy.io\"\n| service_name =~ \"lr-backend||frontend\"\n| user_agent !~ \"Exporter.*\"\n| response_code =~ \"2..\"\n[$__interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "3xx requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"istio-proxy\"}\n| json\n| __error__=\"\"\n| authority =~ \".*dummy.io\"\n| service_name =~ \"lr-backend||frontend\"\n| user_agent !~ \"Exporter.*\"\n| response_code =~ \"3..\"\n[$__interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Total byte sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(sum_over_time({container=\"istio-proxy\"}\n| json \n| __error__=\"\" \n| authority =~ \".*dummy.io\"\n| service_name =~ \"lr-backend||frontend\"\n| user_agent !~ \"Exporter.*\"\n| unwrap bytes_sent [$__interval]))",
     "legendFormat": "$label_value"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "options": {
    "content": "# Dashboard Explained\n## Successful Login Count\n- Counts the number of successful login attempts to the API Gateway `/auth/login`.\n\n## HTTP Status Count\n- Counts requests per HTTP status code for the `lr-backend` and `frontend` services.\n\n> Note: Click the Hyperlink Icon to open Log Query."
   }
  },
  {
   "title": "4xx requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"istio-proxy\"}\n| json\n| __error__=\"\"\n| authority =~ \".*dummy.io\"\n| service_name =~ \"lr-backend||frontend\"\n| user_agent !~ \"Exporter.*\"\n| response_code =~ \"4..\"\n[$__interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "5xx requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"istio-proxy\"}\n| json\n| __error__=\"\"\n| authority =~ \".*dummy.io\"\n| service_name =~ \"lr-backend||frontend\"\n| user_agent !~ \"Exporter.*\"\n| response_code =~ \"5..\"\n[$__interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "% of 4xx + 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"istio-proxy\"}\n| json\n| __error__=\"\"\n| authority =~ \".*dummy.io\"\n| service_name =~ \"lr-backend||frontend\"\n| user_agent !~ \"Exporter.*\"\n| response_code =~ \"4..||5..\"\n[$__interval]))\n/\nsum(count_over_time({container=\"istio-proxy\"}\n| json\n| __error__=\"\"\n| authority =~ \".*dummy.io\"\n| service_name =~ \"lr-backend||frontend\"\n| user_agent !~ \"Exporter.*\"\n| response_code =~ \"2..||3..||4..||5..\"\n[$__interval]))"
    }
   ]
  },
  { "title": "Acquisition and Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top 10 longest response paths  3 hours",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10,\n  max_over_time({\n    container=\"istio-proxy\"\n  }\n  !~ `.ico|.svg|.css|.png|.txt|.js|.xml`\n  | json\n  | authority =~ \".*dummy.io\"\n  | path !~ `/socket.*||/health.*`\n  | __error__=``\n  | unwrap duration\n  [3h])\n  by (path)\n)",
     "legendFormat": "{{path}} "
    }
   ]
  },
  {
   "title": "Top 10 visitor IPs",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (x_forwarded_for) (count_over_time({container=\"istio-proxy\"}\r\n| json \r\n| authority =~ \".*dummy.io\"\r\n| service_name = \"lr-backend\"\r\n| x_forwarded_for != \"\" \r\n| x_forwarded_for !~ `.*:.*`\r\n| x_forwarded_for !~ `^10\\..*|^172\\.(1[6-9]|2[0-9]|3[0-1])\\..*|^192\\.168\\..*` \r\n[$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top 10 User Types",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (user_agent) (count_over_time({container=\"istio-proxy\"}\r\n| json \r\n| __error__=``\r\n| authority =~ \".*dummy.io\"\r\n| service_name = \"lr-backend\"\r\n| x_forwarded_for != \"\" \r\n| x_forwarded_for !~ `.*:.*`\r\n| x_forwarded_for !~ `^10\\..*|^172\\.(1[6-9]|2[0-9]|3[0-1])\\..*|^192\\.168\\..*` \r\n[$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  }
 ]
}