secret:
    key1: ENC[AES256_GCM,data:xK4ARFWnB99ifSejGByy3CByoc/55Bx8WcykihgMhftpoE7lUY/Dmlt/Frk=,iv:rjw1SDPWAaqlUPIJBh+RGxd+2D9u7uD5iskXlm9iLjM=,tag:nIGIC1MGGUwdvmF7IxxMwA==,type:str]
    key2: ENC[AES256_GCM,data:ZTKGn9a3MJakcIGtMUqEYT+myXv1TmsyvlP9EZEfUP0Jxy98FVDl0dvTNAs=,iv:pQI13dhjjqJ8RSggz/AZCa0vxqN3GJA+EueUZwow9gY=,tag:EIVf6emfej4UFVy7cjp9XQ==,type:str]
    key3: ENC[AES256_GCM,data:xaLYxU8LQLwHrZEkGWBwzO8B1EphLY8xQKLzA1pIK8NyPJkjQyZrz86uOJI=,iv:kb7MQbVBdLWObSskQ5tDVv1/NbdwiNEY1jI7jKvG6QY=,tag:skFbZcm4OlYIXEtjVhInAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150ragpc4lx6lnerxmk8azclsc5jwwz984ewfgdlxtm9k6z0a7smqgwx66l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuL0ZmN2tuSXVjeGRMeWQv
            ZFltNEJ1T3d3eWVVQ3pxSlgxYnFIUlJYSFM4Cnk3a2tQWXBjMjNVZzJjUEg2dEVX
            ODFyYnVwTWt3MldsbmQ5M2pwNFErNVUKLS0tIDJIL2p5QkZjNjVRVEJhSkVQYi9T
            M28wbkVwUUdQNlRFVEVpWHRTYmxpTGcKpeLWL2NnHkthJvrniu+pSeqkQOBOeGmp
            Tm5jRmU1VqYDGvPfIq2AjU44Wi9XKnZpNrDSrzvYr1PJ2du9K4t8dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T16:05:32Z"
    mac: ENC[AES256_GCM,data:mfE5ImPwIybD5vECfIF73WsplKBBsdsVtMhOMYogKYq0syKOKWAq/FwS3j5AClAySFjIKHeZuY9ID/jN2r5P3Pv6JpkTKVNbWmzCTiDG99C/OEfuVo1YdU3gkywNDA070gOG0SryR0Cdlql9fhfgsw15TbOQzvcZ4mSDdQaIlDY=,iv:sl8ZMhUb+MCFnX8ojnh/u7EeZ5FkSFpcGNSEqy5tLSU=,tag:XRejFwufGH55JPTZk2fodQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
