{{- $keys := list }}
{{- if .Values.secret.key1 }}{{ $keys = append $keys .Values.secret.key1 }}{{ end }}
{{- if .Values.secret.key2 }}{{ $keys = append $keys .Values.secret.key2 }}{{ end }}
{{- if .Values.secret.key3 }}{{ $keys = append $keys .Values.secret.key3 }}{{ end }}
{{- if .Values.secret.key4 }}{{ $keys = append $keys .Values.secret.key4 }}{{ end }}
{{- if .Values.secret.key5 }}{{ $keys = append $keys .Values.secret.key5 }}{{ end }}
{{- if empty $keys }}{{ fail "at least one of secret.key1-key5 must be set" }}{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openbao-unseal.fullname" . }}-keys
  labels:
    {{- include "openbao-unseal.labels" . | nindent 4 }}
data:
  keys: {{ join "\n" $keys | b64enc }}
