oauth:
    clientId: ENC[AES256_GCM,data:qc4SuJ6tPwVWtnwtfNm8dt8=,iv:KkCj9iPJ/2mrXbGhIngM+zft11I2tKDsI6wQwCxzJAY=,tag:Xb4htLkecVaL+yXibK7Z1Q==,type:str]
    clientSecret: ENC[AES256_GCM,data:IcTCNbUf1X2pZdABOW+RZR6pHP7TxVb3sb15DqQ2XjAdsNVIFVPhJHqrH6MFeiLoz+8ZPqv58varzi0qQKaH4w==,iv:YJ5SNjh3eQAvbNAy9iY2Wlj2wVeeLhm7i8VuF5RL3m8=,tag:B8XWn/Hi0EJHdF/EsmHXtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age150ragpc4lx6lnerxmk8azclsc5jwwz984ewfgdlxtm9k6z0a7smqgwx66l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZVJnbEVhSThpMHB3anRU
            NmJZV0l4Q283UHo5K3p6akZJcGZIV2pZRVNZCmQrS3RPQm95US9UNlI0RThBVjhN
            RmVTbnpTcVZnRmMvOXJ4Mi9sT3hIUlEKLS0tIHVQRWIwbExhWWV4cTB3VmZ5Mklo
            NzRoMlhjdVY2WGpDU1FSSk1TemZVU0EK80OdTeUccKChPD7VXYx04uSJxSAPEKvr
            O//nSscjgdMVssp6WU1ZhdMEZCVlVgulHTbv7twWJNTI1VnfEA6Yxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T04:37:47Z"
    mac: ENC[AES256_GCM,data:kA/RLioWqH6esS6Qy7j865ak/c9UcYr3AnFsT7xItoGg7sqWUQLTX6mqC49Du0B0UdHMs8oaMDsrPV21Dlu0VuAcOzq827LqDadJCeRuGUsviZZXA31dGWBwDNYryxWy+/SLg9TdAyJGOdAuLfFrgYPrfbpDGhJe2BIC3gXUZtY=,iv:0NkkMQoAz+WQ1tF2PDbEPMvuNyVhgG98fh/5RERxWtI=,tag:PMSR0LKqHBhpLAkVF2xdtQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
